import fs from 'node:fs'
import path from 'node:path'
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest'
import { makeMockProvider, mkTempProjectFromSample, rmTemp, setMockHandler } from './_helpers'

vi.mock('../../src/main/llm', () => ({
  resolveLlmProvider: () => makeMockProvider()
}))

import { runContextCommenter } from '../../src/main/commenter/context-commenter'

const GENERATED_COMMENT = `\
\`\`\`cpp
/*----------------------------------------------------------------------------*/
/*! \\brief Generated by the contextual commenter pipeline.
 *
 * Mock comment that exercises the splice path.
 *
 * \\param [in] args : forwarded from the call site
 * \\return depends on the function
 *
 * \\remark Néant
 */
/*----------------------------------------------------------------------------*/
\`\`\`
`

describe('Commenter contextual pipeline E2E (samples/cpp-demo)', () => {
  let projectRoot: string

  beforeAll(() => {
    projectRoot = mkTempProjectFromSample('samples/cpp-demo')
  })
  afterAll(() => {
    rmTemp(projectRoot)
  })

  it('skips functions deemed sufficient and inserts new comments where the verdict is NO', async () => {
    // Strategy: route the evaluator (which has a `YES|NO | reason` system) by
    // looking at the system prompt; the generator returns the Doxygen block.
    setMockHandler((req) => {
      const lastUser = req.messages.filter((m) => m.role === 'user').pop()?.content ?? ''
      const sys = req.messages.find((m) => m.role === 'system')?.content ?? ''
      const isEvaluator = sys.includes('strict reviewer')
      if (isEvaluator) {
        // Anything from strutil.* is already well documented in the fixture.
        if (lastUser.includes('to_upper') || lastUser.includes('to_lower') || lastUser.includes('trim')) {
          return 'YES | brief, params and return are documented in Doxygen style.'
        }
        return 'NO | no comment block above the function.'
      }
      // Generator path
      return GENERATED_COMMENT
    })

    const filePaths = [
      path.join(projectRoot, 'src/strutil.cpp'),
      path.join(projectRoot, 'src/calculator.cpp')
    ]
    const result = await runContextCommenter({ projectRoot, filePaths })

    expect(result.files).toHaveLength(2)

    // strutil.cpp: every function already has Doxygen above it → all skipped.
    const strutil = result.files.find((f) => f.filePath.endsWith('strutil.cpp'))!
    expect(strutil.commented).toBe(0)
    expect(strutil.skipped).toBe(strutil.plans.length)
    // newContent should equal the original content when nothing was commented.
    expect(strutil.newContent).toBe(strutil.originalContent)

    // calculator.cpp: no functions have Doxygen → all need commenting.
    const calc = result.files.find((f) => f.filePath.endsWith('calculator.cpp'))!
    expect(calc.skipped).toBe(0)
    expect(calc.commented).toBe(calc.plans.length)
    expect(calc.commented).toBeGreaterThanOrEqual(5) // add, multiply, square, sum, average, max_element
    expect(calc.newContent).not.toBe(calc.originalContent)
    expect(calc.newContent).toContain('Generated by the contextual commenter pipeline')

    // Sanity: the original function bodies are preserved (no rename / type change).
    expect(calc.newContent).toContain('int add(int a, int b)')
    expect(calc.newContent).toContain('int multiply(int a, int b)')
    expect(calc.newContent).toContain('return a + b;')
  })
})
