import { Marp } from '@marp-team/marp-core'

export type PreviewResult = {
  /** Self-contained HTML document (CSS inlined) safe to drop into an <iframe srcDoc>. */
  html: string
  /** Raw rendered HTML body (without surrounding doc) for advanced callers. */
  body: string
  /** Stylesheet generated by Marp for the chosen theme. */
  css: string
}

/**
 * Render Marp Markdown to a self-contained HTML document.
 * The result is meant to be displayed in a sandboxed <iframe srcDoc>;
 * Marp's CSS is inlined in <style> so no external requests are needed.
 */
export function renderMarpPreview(markdown: string): PreviewResult {
  const marp = new Marp({
    html: false, // never allow raw <script>/<iframe> from the model
    script: false,
    inlineSVG: true
  })
  const { html: body, css } = marp.render(markdown, { htmlAsArray: false })

  const html = `<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; font-src data:">
<style>${css}\nhtml,body{margin:0;padding:0;background:#fff;color:#111}</style>
</head>
<body>${body}</body>
</html>`

  return { html, body, css }
}
